import { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Dropbox } from 'dropbox';

const token =
  'sl.A6znWBeiSThYrN3_sHS4yVJX2wGIHJZlxjq2hhH8AiKQGKxGwXV70vhwJueCDCculOhmbaQmNTH48UIxG3Hke7x19Gpn9onT-tL2SVKBNtH8SvOcQZSU-YZNxOvToCq8DKa4uQu34KFk';

const Home: NextPage = () => {
  const [listOfQueries, setListOfQueries] = useState<any>();
  useEffect(() => {
    gettingDropboxInfo();
  }, []);

  const gettingDropboxInfo = async () => {
    const dropBox = new Dropbox({ accessToken: token });

    const res = await dropBox.filesListFolder({ path: '/Otoli Document' });
    setListOfQueries(res.result.entries);
    console.log('dropBoxInfo', res);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {listOfQueries &&
          listOfQueries.map((entry: any) => <p key={entry.id}>{entry.name}</p>)}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
